version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local:1.16.0
    container_name: app-dynamodb
    hostname: app-dynamodb
    volumes:
      - app_dynamodb:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    restart: unless-stopped

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    container_name: app-dynamodb_admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    restart: unless-stopped

  dynamodb_migrator:
    image: amazon/aws-cli
    container_name: app-dynamodb_migrator
    working_dir: /home/dynamodblocal
    command: dynamodb create-table --cli-input-json file://tables/photos.json --endpoint-url http://dynamodb:8000
    volumes:
      - ./schema:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=everything_is_awesome
      - AWS_SECRET_ACCESS_KEY=open_sesame_street!
      - AWS_DEFAULT_REGION=eu-west-2
    depends_on:
      - dynamodb

  dynamodb_seeder:
    image: amazon/aws-cli
    container_name: app-dynamodb_seeder
    working_dir: /home/dynamodblocal
    command: dynamodb batch-write-item --request-items file://seeds/photos.json --endpoint-url http://dynamodb:8000
    volumes:
      - ./schema:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=everything_is_awesome
      - AWS_SECRET_ACCESS_KEY=open_sesame_street!
      - AWS_DEFAULT_REGION=eu-west-2
    depends_on:
      - dynamodb_migrator
      - dynamodb
    restart: on-failure

volumes:
  app_dynamodb:
    driver: local
